apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gah3o8snj-python
  janus-idp.io/tekton: gah3o8snj-python
  backstage.io/kubernetes-id: gah3o8snj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gah3o8snj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
