apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gah3o8snj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gah3o8snj-python 
  name: gah3o8snj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gah3o8snj-python 
